apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres" # This service must be defined as a headless service.
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeName: dev-app-01
      containers:
      - name: postgres
        image: postgres:16
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: dev-pg-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: dev-pg-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: dev-pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-pg-secret
              key: POSTGRES_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: dev-pg-storage
    spec:
      storageClassName: ""
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 20Gi
