apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pg-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  claimRef:
    namespace: chatbot
    name: dev-pg-storage-postgres-0
  nfs:
    server: 172.16.1.32
    path: /data/dev/postgres
  persistentVolumeReclaimPolicy: Retain
