apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-vectordb-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.16.1.32
    path: /data/prod/vectordb
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-vectordb-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: prod-vectordb-pv
  storageClassName: ""
