apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-rabbitmq-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.16.1.32
    path: /data/dev/rabbitmq
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-rabbitmq-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: dev-rabbitmq-pv
  storageClassName: ""
